repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
#  - id: check-docstring-first
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/sirosen/texthooks
  rev: "0.5.0"
  hooks:
  - id: fix-ligatures
  - id: fix-smartquotes

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: "23.7.0" # Keep in sync with blacken-docs
  hooks:
  - id: black
    exclude: ^docs/conf\.py$

- repo: https://github.com/asottile/blacken-docs
  rev: 1.15.0
  hooks:
  - id: "blacken-docs"
    additional_dependencies:
    - black==23.7.0 # keep in sync with black hook

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.282
  hooks:
  - id: ruff
    args: ["--fix", "--show-fixes"]

- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.5"
  hooks:
  - id: codespell
    exclude: "(.png|.svg|^_version.py)$"
    args: ["-L", "ba,endwhile,unparseable"]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: "v1.10.0"
  hooks:
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal

- repo: https://github.com/henryiii/check-sdist
  rev: "v0.1.2"
  hooks:
   - id: check-sdist
     args: [--inject-junk]
     additional_dependencies:
     - hatch-fancy-pypi-readme
     - hatch-vcs
     - hatchling

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v1.4.1"
  hooks:
  - id: mypy
    files: ^(skbuild|tests)
    exclude: ^tests/samples
    additional_dependencies:
    - cmake
    - ninja
    - packaging
    - pytest
    - tomli
    - types-requests
    - types-setuptools>=67.6.0.5
